// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD53kyH7hYaoD5GElLWbeccaow2dkNzvX0',
    appId: '1:514748968816:web:ddc8abcc810b00d8ada9b5',
    messagingSenderId: '514748968816',
    projectId: 'outflow-bef12',
    authDomain: 'outflow-bef12.firebaseapp.com',
    storageBucket: 'outflow-bef12.firebasestorage.app',
    measurementId: 'G-YXYL503P0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQdZeGAlWtZcGaL7z-ozPMTnqoJIVfCN8',
    appId: '1:514748968816:android:a37c74078bc30826ada9b5',
    messagingSenderId: '514748968816',
    projectId: 'outflow-bef12',
    storageBucket: 'outflow-bef12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWt1ttIeV_r0QPMR5NXBkhBOTzvxkav08',
    appId: '1:514748968816:ios:1ecf5d969d4e1436ada9b5',
    messagingSenderId: '514748968816',
    projectId: 'outflow-bef12',
    storageBucket: 'outflow-bef12.firebasestorage.app',
    iosBundleId: 'com.example.outflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWt1ttIeV_r0QPMR5NXBkhBOTzvxkav08',
    appId: '1:514748968816:ios:1ecf5d969d4e1436ada9b5',
    messagingSenderId: '514748968816',
    projectId: 'outflow-bef12',
    storageBucket: 'outflow-bef12.firebasestorage.app',
    iosBundleId: 'com.example.outflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD53kyH7hYaoD5GElLWbeccaow2dkNzvX0',
    appId: '1:514748968816:web:800b2919c48f86f5ada9b5',
    messagingSenderId: '514748968816',
    projectId: 'outflow-bef12',
    authDomain: 'outflow-bef12.firebaseapp.com',
    storageBucket: 'outflow-bef12.firebasestorage.app',
    measurementId: 'G-YCGY6XRLNB',
  );
}
